### ISSUE TITLE
INSERT Not working 

### ISSUE THREAD

**Issue by DsWeb19778** [brandenc40/flask_mysql_connector#2]
THis is my code :
```
@app.route("/news")
def news():
    cur = db.new_cursor(dictionary=True)
    query = "INSERT INTO emails(email) VALUES('test@gmail.com')"
    cur.execute(query)
    cur.close()
```
after run nothung happen
but select working fine any soul for this problem

**Comment by brandenc40** [comment]
I believe you just need to commit your transaction after running insert or the insert won't show in the database

**Comment by DsWeb19778** [comment]
when i commit say : AttributeError: 'MySQL' object has no attribute 'commit'

**Comment by DsWeb19778** [comment]
Thanks dud works fine ... Nice 
Have a nice day

**Comment by Holybasil** [comment]
I think `mysql.connection.commit()` should appear in the doc.

**Comment by dsweb19778** [comment]
@Holybasil haha yes lol I was having the same problem
