### ISSUE TITLE
multiple dB connections is not supporting

### ISSUE THREAD

**Issue by praveendp526** [brandenc40/flask_mysql_connector#3]
I have tried to connect with multiple databases using mysql_connector, it is working fine for some time. later it is showing errors like
mysql.connector.errors.OperationalError: MySQL Connection not available.

**Comment by brandenc40** [comment]
Ah yeah it's not currently designed to support usage of two separate MySQL objects. It's using the same key "mysql_db" in the app context stack which may be causing issues. I think for that to work it will need to allow you to pass an arg to optionally define your own key so the two objects don't fight over the same key. I can work on a fix this week.

**Comment by brandenc40** [comment]
I've updated the package so this should be resolved. please use `pip install flask-mysql-connector==1.1.0`. In order to use multiple MySQL db objects you'll need to set a custom app context stack key like so: 
```python
mysql = MySQL(app, ctx_key="num1")
mysql2 = MySQL(app, ctx_key="num2")
```
